export function getPackageJson(name) {
	return {
		name: name,
		private: true,
		version: '0.0.0',
		type: 'module',
		scripts: {
			dev: 'vite',
			build: 'vue-tsc -b && vite build',
			preview: 'vite preview',
			'test:unit': 'vitest',
			eslint: 'eslint .',
			'eslint:fix': 'eslint . --fix',
			stylelint: 'stylelint "**/*.{vue,css,scss,postcss}"',
			'stylelint:fix': 'stylelint "**/*.{vue,css,scss,postcss}" --fix',
			prettier: 'prettier --check .',
			'prettier:fix': 'prettier --write .',
			lint: 'pnpm eslint && pnpm stylelint && pnpm prettier',
			'lint:fix': 'pnpm eslint:fix && pnpm stylelint:fix && pnpm prettier:fix',
		},
		dependencies: {
			'@admin-panel/i18n': 'workspace:*',
			'@admin-panel/lib': 'workspace:*',
			'@admin-panel/ui': 'workspace:*',
			'@element-plus/icons-vue': '^2.3.2',
			'@tanstack/vue-query': '^5.92.1',
			vue: '^3.5.22',
			'vue-router': '^4.5.1',
			'element-plus': '^2.13.0',
		},
		devDependencies: {
			'@admin-panel/eslint-config': 'workspace:*',
			'@admin-panel/prettier-config': 'workspace:*',
			'@admin-panel/stylelint-config': 'workspace:*',
			'@admin-panel/typescript-config': 'workspace:*',
			'@types/node': '^24.9.2',
			'@vitejs/plugin-vue': '^6.0.1',
			typescript: '~5.9.3',
			vite: '^7.1.7',
			'vue-tsc': '^3.1.0',
		},
	}
}
