-- Migration: Venues table
CREATE TABLE IF NOT EXISTS venues (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    subtitle TEXT,
    description_html TEXT,
    phone TEXT,
    address TEXT NOT NULL,
    city TEXT NOT NULL DEFAULT 'Москва',
    metro_station TEXT,
    metro_distance_minutes INT,
    metro_distance_text TEXT,
    metro_line_color TEXT,
    coordinates_lat DOUBLE PRECISION,
    coordinates_lng DOUBLE PRECISION,
    average_check INT DEFAULT 0,
    banquet_price_from INT DEFAULT 0,
    rent_price_hour INT DEFAULT 0,
    corkage_fee_has BOOLEAN DEFAULT false,
    corkage_fee_desc TEXT,
    price_level TEXT DEFAULT '$$$',
    halls_count INT DEFAULT 1,
    capacity_banquet TEXT,
    capacity_buffet TEXT,
    capacity_theater TEXT,
    area_sqm TEXT,
    working_hours_weekdays TEXT,
    working_hours_weekends TEXT,
    rating_score DOUBLE PRECISION DEFAULT 5.0,
    rating_reviews_count INT DEFAULT 0,
    venue_types TEXT[] DEFAULT '{}',
    features TEXT[] DEFAULT '{}',
    cuisines TEXT[] DEFAULT '{}',
    services TEXT[] DEFAULT '{}',
    parking TEXT,
    equipment TEXT[] DEFAULT '{}',
    halls JSONB DEFAULT '[]',
    rooms JSONB DEFAULT '[]',
    gallery_photos TEXT[] DEFAULT '{}',
    video_tour_url TEXT,
    has_online_tour BOOLEAN DEFAULT true,
    faq JSONB DEFAULT '[]',
    feed JSONB DEFAULT '[]',
    status TEXT NOT NULL DEFAULT 'published',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_venues_slug ON venues (slug);
CREATE INDEX IF NOT EXISTS idx_venues_status ON venues (status);
