ALTER TABLE media DROP COLUMN IF EXISTS optimized_path;
ALTER TABLE media DROP COLUMN IF EXISTS blurhash;
ALTER TABLE media DROP COLUMN IF EXISTS width;
ALTER TABLE media DROP COLUMN IF EXISTS height;
