import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))

// We'll use a simple fetch since we might not want to depend on complex libs in a small script
// or we can use ofetch if we run it via node with proper resolution.
// Since ofetch is in dependencies, it should be available if we run from package root.

async function generate() {
	const API_URL = process.env.VITE_API_URL || 'http://localhost:8000'
	const TARGET_FILE = path.resolve(__dirname, '../src/types.ts')

	console.log(`Fetching translations from ${API_URL}...`)

	try {
		const response = await fetch(`${API_URL}/api/v1/i18n?limit=10000`)
		if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`)

		const json = await response.json()
		const items = json.data?.items || []

		if (items.length === 0) {
			console.warn('No translations found. Skipping type generation.')
			return
		}

		const keys = [...new Set(items.map((i) => i.key))].sort()
		const namespaces = [...new Set(keys.map((k) => k.split('.')[0]))].sort()

		const typeContent = `/**
 * AUTO-GENERATED FILE. DO NOT MODIFY.
 * This file was generated by scripts/generate-types.mjs
 */

export type TranslationKey = 
${keys.map((k) => `  | '${k}'`).join('\n')};

export type TranslationNamespace = 
${namespaces.map((ns) => `  | '${ns}'`).join('\n')};

export interface TranslationParams {
  [key: string]: string | number | boolean;
}
`

		fs.mkdirSync(path.dirname(TARGET_FILE), { recursive: true })
		fs.writeFileSync(TARGET_FILE, typeContent)
		console.log(`Successfully generated i18n types to ${TARGET_FILE}`)
	} catch (e) {
		console.error('Failed to generate i18n types:', e.message)
		process.exit(1)
	}
}

generate()
