import fs from 'fs'
import path from 'path'
import type { Plugin } from 'vite'
import { optimize } from 'svgo'

interface Options {
	inputDir: string
	outputTs: string
	prefix?: string
}

export default function svgSpriteInlinePlugin(options: Options): Plugin {
	const { inputDir, outputTs, prefix = '' } = options

	return {
		name: 'vite-svg-sprite-inline-plugin',

		buildStart() {
			const absInputDir = path.resolve(inputDir)
			const absOutputTs = path.resolve(outputTs)
			const outputDir = path.dirname(absOutputTs)

			if (!fs.existsSync(absInputDir)) {
				// eslint-disable-next-line no-console
				console.warn(`[svg-sprite-inline] Input dir not found: ${absInputDir}`)

				return
			}

			const files = fs.readdirSync(absInputDir).filter((f) => f.endsWith('.svg'))

			if (files.length === 0) {
				// eslint-disable-next-line no-console
				console.warn(`[svg-sprite-inline] No SVG files in ${absInputDir}`)

				return
			}

			// Создаём выходную директорию, если её нет
			if (!fs.existsSync(outputDir)) {
				fs.mkdirSync(outputDir, { recursive: true })
			}

			let spriteSymbols = ''
			const iconNames: string[] = []

			for (const file of files) {
				const filePath = path.join(absInputDir, file)
				const svgContent = fs.readFileSync(filePath, 'utf8')

				const viewBoxMatch = svgContent.match(/viewBox=["']([^"']+)["']/i)
				const viewBox = viewBoxMatch ? viewBoxMatch[1] : '0 0 24 24'

				const result = optimize(svgContent, {
					plugins: [
						'removeDoctype',
						'removeXMLProcInst',
						'removeComments',
						'removeMetadata',
						'removeTitle',
						'removeDesc',
						'removeUselessDefs',
						'removeEditorsNSData',
						'removeEmptyAttrs',
						'removeHiddenElems',
						'removeEmptyText',
						'removeEmptyContainers',
						'cleanupAttrs',
						'minifyStyles',
						'convertStyleToAttrs',
						'convertColors',
						'convertPathData',
						'convertTransform',
						'removeUnknownsAndDefaults',
						'removeNonInheritableGroupAttrs',
						'removeUselessStrokeAndFill',
						'cleanupEnableBackground',
						'removeRasterImages',
						'mergePaths',
						'inlineStyles',
					],
				})

				const iconName = path.basename(file, '.svg')
				const id = prefix ? `${prefix}-${iconName}` : iconName

				iconNames.push(id)

				spriteSymbols += `<symbol id="${id}" viewBox="${viewBox}">${result.data}</symbol>`
			}

			const spriteString = `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">${spriteSymbols}</svg>`
			const escapedSprite = spriteString.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$')

			const tsContent = `// Auto-generated by vite-svg-sprite-inline-plugin
export const SVG_SPRITE = \`${escapedSprite}\`;

export type IconName = ${iconNames.map((n) => `'${n}'`).join(' | ')};
export const iconNames = [${iconNames.map((n) => `'${n}'`).join(', ')}] as const;
`

			fs.writeFileSync(absOutputTs, tsContent)

			// eslint-disable-next-line no-console
			console.log(`[svg-sprite-inline] Generated: ${absOutputTs}`)
		},
	}
}
