/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	'/api/v1/about': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_about']
		put: operations['update_about']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/engagement': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_engagement_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/funnel': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_funnel_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/referrals': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_referral_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/retention': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_retention_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/session': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['start_session']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/summary': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_summary_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/track': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['track_event']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/analytics/traffic': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_traffic_stats']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/login': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['login']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/logout': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['logout']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/logout/other': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['logout_other_devices']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/refresh': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['refresh']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/register': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['register']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/auth/register/key': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['check_register_key']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/content/entries': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['create_entry']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/content/entries/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_entry']
		put?: never
		post?: never
		delete: operations['delete_entry']
		options?: never
		head?: never
		patch: operations['update_entry']
		trace?: never
	}
	'/api/v1/content/entries/{id}/versions': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_entry_versions']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/content/entries/{id}/versions/{version_id}/rollback': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['rollback_entry_version']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/content/schemas': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_schemas']
		put?: never
		post: operations['create_schema']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/content/schemas/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_schema']
		put?: never
		post?: never
		delete: operations['delete_schema']
		options?: never
		head?: never
		patch: operations['update_schema']
		trace?: never
	}
	'/api/v1/content/schemas/{schema_id}/entries': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_entries']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/features': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_features']
		put?: never
		post: operations['update_features']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/guests': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_guests']
		put: operations['update_guests']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/i18n': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_all']
		put?: never
		post: operations['create_or_update']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/i18n/languages': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_languages']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/i18n/namespaces': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_namespaces']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/i18n/{dict_key}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_by_dict_key']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/i18n/{key}/{locale}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post?: never
		delete: operations['delete_one']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/media': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_all_media']
		put?: never
		post: operations['upload_media']
		delete: operations['delete_all_media']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/media/{uuid}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_media_by_uuid']
		put: operations['update_media']
		post?: never
		delete: operations['delete_media_by_uuid']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mfe': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_all']
		put?: never
		post: operations['create']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mfe/manifest': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_manifest']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/mfe/{id}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put: operations['update']
		post?: never
		delete: operations['delete_one']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/platforms': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_platforms']
		put: operations['update_platforms']
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/system/health': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_health']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/system/stats/stream': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_stats_stream']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/user': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['create_user']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/user/me': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_me']
		put?: never
		post?: never
		delete?: never
		options?: never
		head?: never
		patch: operations['update_me']
		trace?: never
	}
	'/api/v1/user/me/password': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get?: never
		put?: never
		post: operations['change_password']
		delete?: never
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
	'/api/v1/user/{uuid}': {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		get: operations['get_user_by_uuid']
		put?: never
		post?: never
		delete: operations['delete_user_by_uuid']
		options?: never
		head?: never
		patch?: never
		trace?: never
	}
}
export type webhooks = Record<string, never>
export interface components {
	schemas: {
		AboutResponseDTO: {
			description: string
			hero_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			hero_guide_uuid?: string | null
			leadership: components['schemas']['LeadershipDTO']
			leadership_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			leadership_guide_uuid?: string | null
			news: components['schemas']['NewsDTO']
			news_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			news_guide_uuid?: string | null
			opportunities: components['schemas']['OpportunitiesDTO']
			opportunities_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			title: string
			who_we_are: components['schemas']['WhoWeAreItemDTO'][]
			who_we_are_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			who_we_are_guide_uuid?: string | null
		}
		AdditionalServiceDTO: {
			icon?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			icon_uuid?: string | null
			text: string
		}
		AnalyticsSummaryDto: {
			/** Format: int64 */
			avg_session_duration: number
			/** Format: float */
			clicks_trend: number
			/** Format: int64 */
			page_views: number
			/** Format: float */
			session_trend: number
			/** Format: int64 */
			total_clicks: number
			/** Format: int64 */
			total_visitors: number
			/** Format: float */
			views_trend: number
			/** Format: float */
			visitors_trend: number
		}
		ApiPaginationDTO_MediaItemDTO: {
			items: {
				alt?: string | null
				category?: string | null
				/** Format: date-time */
				createdAt: string
				extension?: string | null
				mediaType: components['schemas']['MediaType']
				name?: string | null
				/** Format: int64 */
				sizeBytes: number
				source: string
				tags?: string[] | null
				title?: string | null
				url: string
				uuid: string
			}[]
			pagination: components['schemas']['PaginationDTO']
		}
		ApiPaginationDTO_TranslationDTO: {
			items: {
				/** Format: date-time */
				created_at: string
				/** Format: uuid */
				id: string
				key: string
				locale: string
				/** Format: date-time */
				updated_at: string
				value: string
			}[]
			pagination: components['schemas']['PaginationDTO']
		}
		ApiResponseWithPagination_MediaItemDTO: {
			data?: null | components['schemas']['ApiPaginationDTO_MediaItemDTO']
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponseWithPagination_TranslationDTO: {
			data?: null | components['schemas']['ApiPaginationDTO_TranslationDTO']
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_AboutResponseDTO: {
			data?: {
				description: string
				hero_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				hero_guide_uuid?: string | null
				leadership: components['schemas']['LeadershipDTO']
				leadership_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				leadership_guide_uuid?: string | null
				news: components['schemas']['NewsDTO']
				news_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				news_guide_uuid?: string | null
				opportunities: components['schemas']['OpportunitiesDTO']
				opportunities_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				opportunities_guide_uuid?: string | null
				title: string
				who_we_are: components['schemas']['WhoWeAreItemDTO'][]
				who_we_are_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				who_we_are_guide_uuid?: string | null
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_AnalyticsSummaryDto: {
			data?: {
				/** Format: int64 */
				avg_session_duration: number
				/** Format: float */
				clicks_trend: number
				/** Format: int64 */
				page_views: number
				/** Format: float */
				session_trend: number
				/** Format: int64 */
				total_clicks: number
				/** Format: int64 */
				total_visitors: number
				/** Format: float */
				views_trend: number
				/** Format: float */
				visitors_trend: number
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_AuthResponseDTO: {
			data?: {
				/** Format: int64 */
				access_expires_in: number
				access_token: string
				/** Format: int64 */
				refresh_expires_in: number
				refresh_token: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_ContentEntry: {
			data?: {
				/** Format: date-time */
				created_at: string
				data: Record<string, never>
				i18n: Record<string, never>
				/** Format: uuid */
				id: string
				/** Format: uuid */
				schema_id: string
				slug: string
				status: components['schemas']['ContentEntryStatus']
				/** Format: date-time */
				updated_at: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_ContentSchema: {
			data?: {
				/** Format: date-time */
				created_at: string
				fields: components['schemas']['FieldDefinition'][]
				/** Format: uuid */
				id: string
				is_singleton: boolean
				name: string
				slug: string
				/** Format: date-time */
				updated_at: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_GuestsResponseDTO: {
			data?: {
				additional_services: components['schemas']['AdditionalServiceDTO'][]
				additional_services_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				additional_services_guide_uuid?: string | null
				hero_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				hero_guide_uuid?: string | null
				interaction_cards: components['schemas']['InteractionCardDTO'][]
				interaction_cards_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				interaction_cards_guide_uuid?: string | null
				opportunities: components['schemas']['GuestOpportunityItemDTO'][]
				opportunities_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				opportunities_guide_uuid?: string | null
				search_promo: components['schemas']['SearchPromoDTO']
				search_promo_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				search_promo_guide_uuid?: string | null
				title: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_MediaItemDTO: {
			data?: {
				alt?: string | null
				category?: string | null
				/** Format: date-time */
				createdAt: string
				extension?: string | null
				mediaType: components['schemas']['MediaType']
				name?: string | null
				/** Format: int64 */
				sizeBytes: number
				source: string
				tags?: string[] | null
				title?: string | null
				url: string
				uuid: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_PlatformsResponseDTO: {
			data?: {
				description: string
				hero_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				hero_guide_uuid?: string | null
				opportunities: components['schemas']['OpportunitiesDTO']
				opportunities_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				opportunities_guide_uuid?: string | null
				title: string
				tools_and_services: components['schemas']['ToolsAndServicesDTO']
				tools_guide?: null | components['schemas']['MediaDTO']
				/** Format: uuid */
				tools_guide_uuid?: string | null
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_SessionResponseDto: {
			data?: {
				/** Format: uuid */
				id: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_TrafficStatsDto: {
			data?: {
				dau: number[]
				labels: string[]
				sessions: number[]
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_UserResponseDTO: {
			data?: {
				avatar?: string | null
				/** Format: date */
				birth_date?: string | null
				city?: string | null
				/** Format: date-time */
				created_at: string
				email: string
				first_name?: string | null
				gender?: string | null
				last_name?: string | null
				phone?: string | null
				role: components['schemas']['UserRole']
				second_name?: string | null
				status: components['schemas']['UserStatus']
				street?: string | null
				/** Format: date-time */
				updated_at: string
				/** Format: uuid */
				uuid: string
			}
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Value: {
			data?: unknown
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_CohortRowDto: {
			data?: {
				cohort_month: string
				retention_rates: number[]
				/** Format: int64 */
				total_users: number
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_ContentEntry: {
			data?: {
				/** Format: date-time */
				created_at: string
				data: Record<string, never>
				i18n: Record<string, never>
				/** Format: uuid */
				id: string
				/** Format: uuid */
				schema_id: string
				slug: string
				status: components['schemas']['ContentEntryStatus']
				/** Format: date-time */
				updated_at: string
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_ContentEntryVersion: {
			data?: {
				comment?: string | null
				/** Format: date-time */
				created_at: string
				/** Format: uuid */
				created_by?: string | null
				data: Record<string, never>
				/** Format: uuid */
				entry_id: string
				i18n: Record<string, never>
				/** Format: uuid */
				id: string
				/** Format: int32 */
				version_number: number
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_ContentSchema: {
			data?: {
				/** Format: date-time */
				created_at: string
				fields: components['schemas']['FieldDefinition'][]
				/** Format: uuid */
				id: string
				is_singleton: boolean
				name: string
				slug: string
				/** Format: date-time */
				updated_at: string
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_EngagementStatsDto: {
			data?: {
				/** Format: int64 */
				clicks: number
				entity_id: string
				/** Format: int64 */
				views: number
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_FunnelStepDto: {
			data?: {
				/** Format: int64 */
				count: number
				name: string
				/** Format: float */
				percentage: number
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_LanguageDTO: {
			data?: {
				code: string
				name: string
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_Mfe: {
			data?: {
				category: string
				config: unknown
				/** Format: date-time */
				created_at: string
				display_name: string
				enabled: boolean
				icon?: string | null
				/** Format: uuid */
				id: string
				module: string
				name: string
				/** Format: int32 */
				order_index: number
				scope: string
				/** Format: date-time */
				updated_at: string
				url: string
				version?: string | null
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_NamespaceDTO: {
			data?: {
				/** Format: date-time */
				created_at: string
				description?: string | null
				/** Format: uuid */
				id: string
				is_dynamic: boolean
				name: string
				/** Format: date-time */
				updated_at: string
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		ApiResponse_Vec_ReferralDto: {
			data?: {
				/** Format: int64 */
				count: number
				/** Format: float */
				percentage: number
				source: string
			}[]
			errors?: {
				[key: string]: string[]
			} | null
			messages?: string[] | null
		}
		AuthRefreshTokenDTO: {
			refresh_token: string
		}
		AuthRequestDTO: {
			email: string
			password: string
		}
		AuthResponseDTO: {
			/** Format: int64 */
			access_expires_in: number
			access_token: string
			/** Format: int64 */
			refresh_expires_in: number
			refresh_token: string
		}
		ChangePasswordDTO: {
			new_password: string
			old_password: string
		}
		CheckEmailCodeDTO: {
			key: string
		}
		CohortRowDto: {
			cohort_month: string
			retention_rates: number[]
			/** Format: int64 */
			total_users: number
		}
		ContentEntry: {
			/** Format: date-time */
			created_at: string
			data: Record<string, never>
			i18n: Record<string, never>
			/** Format: uuid */
			id: string
			/** Format: uuid */
			schema_id: string
			slug: string
			status: components['schemas']['ContentEntryStatus']
			/** Format: date-time */
			updated_at: string
		}
		/** @enum {string} */
		ContentEntryStatus: 'draft' | 'review' | 'published'
		ContentEntryVersion: {
			comment?: string | null
			/** Format: date-time */
			created_at: string
			/** Format: uuid */
			created_by?: string | null
			data: Record<string, never>
			/** Format: uuid */
			entry_id: string
			i18n: Record<string, never>
			/** Format: uuid */
			id: string
			/** Format: int32 */
			version_number: number
		}
		ContentSchema: {
			/** Format: date-time */
			created_at: string
			fields: components['schemas']['FieldDefinition'][]
			/** Format: uuid */
			id: string
			is_singleton: boolean
			name: string
			slug: string
			/** Format: date-time */
			updated_at: string
		}
		CreateContentEntryDTO: {
			data: unknown
			i18n?: unknown
			/** Format: uuid */
			schema_id: string
			slug: string
			status?: null | components['schemas']['ContentEntryStatus']
		}
		CreateMediaDTO: {
			alt?: string | null
			category?: string | null
			/** Format: binary */
			file: string
			name?: string | null
			source?: string | null
			tags?: string[] | null
			title?: string | null
		}
		CreateMfeDto: {
			category?: string | null
			config?: unknown
			display_name: string
			icon?: string | null
			module: string
			name: string
			/** Format: int32 */
			order_index?: number | null
			scope: string
			url: string
			version?: string | null
		}
		CreateSchemaDTO: {
			fields: components['schemas']['FieldDefinition'][]
			is_singleton?: boolean
			name: string
			slug: string
		}
		CreateTranslationDTO: {
			key: string
			locale: string
			value: string
		}
		CreateUserDTO: {
			avatar?: string | null
			/** Format: uuid */
			avatar_uuid?: string | null
			/** Format: date */
			birth_date?: string | null
			city?: string | null
			email: string
			first_name?: string | null
			gender?: string | null
			last_name?: string | null
			password: string
			phone?: string | null
			role?: null | components['schemas']['UserRole']
			second_name?: string | null
			status?: null | components['schemas']['UserStatus']
			street?: string | null
		}
		EngagementStatsDto: {
			/** Format: int64 */
			clicks: number
			entity_id: string
			/** Format: int64 */
			views: number
		}
		EntryFilterQuery: {
			search?: string | null
		}
		FeatureFlag: {
			description: string
			enabled: boolean
			id: string
			name: string
		}
		FeatureFlagsUpdate: {
			flags: components['schemas']['FeatureFlag'][]
		}
		FieldDefinition: {
			field_type: components['schemas']['FieldType']
			label: string
			multiple?: boolean
			name: string
			relation_to?: string | null
			required?: boolean
		}
		/** @enum {string} */
		FieldType: 'text' | 'rich_text' | 'number' | 'boolean' | 'media' | 'date' | 'relation'
		FunnelStepDto: {
			/** Format: int64 */
			count: number
			name: string
			/** Format: float */
			percentage: number
		}
		GuestOpportunityItemDTO: {
			button_text: string
			icon?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			icon_uuid?: string | null
			items: string[]
			link: string
			title: string
		}
		GuestsResponseDTO: {
			additional_services: components['schemas']['AdditionalServiceDTO'][]
			additional_services_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			additional_services_guide_uuid?: string | null
			hero_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			hero_guide_uuid?: string | null
			interaction_cards: components['schemas']['InteractionCardDTO'][]
			interaction_cards_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			interaction_cards_guide_uuid?: string | null
			opportunities: components['schemas']['GuestOpportunityItemDTO'][]
			opportunities_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			search_promo: components['schemas']['SearchPromoDTO']
			search_promo_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			search_promo_guide_uuid?: string | null
			title: string
		}
		HealthStatus: {
			db: string
			redis: string
			status: string
		}
		InteractionCardDTO: {
			button_text: string
			icon?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			icon_uuid?: string | null
			link: string
			text: string
			title: string
		}
		LanguageDTO: {
			code: string
			name: string
		}
		LeadershipDTO: {
			description: string
			items: components['schemas']['LeadershipItemDTO'][]
			logo: components['schemas']['MediaDTO']
			title: string
		}
		LeadershipItemDTO: {
			icon: components['schemas']['MediaDTO']
			text: string
		}
		ManifestDto: {
			remotes: components['schemas']['RemoteDto'][]
		}
		MediaDTO: {
			alt?: string | null
			title?: string | null
			url: string
		}
		MediaFilterQuery: {
			category?: string | null
			/** Format: int32 */
			limit?: number | null
			media_type?: string | null
			/** Format: int32 */
			page?: number | null
			search?: string | null
			sort_by?: string | null
			sort_order?: string | null
			source?: string | null
			tags?: string | null
		}
		MediaItemDTO: {
			alt?: string | null
			category?: string | null
			/** Format: date-time */
			createdAt: string
			extension?: string | null
			mediaType: components['schemas']['MediaType']
			name?: string | null
			/** Format: int64 */
			sizeBytes: number
			source: string
			tags?: string[] | null
			title?: string | null
			url: string
			uuid: string
		}
		/** @enum {string} */
		MediaType: 'image' | 'video' | 'icon' | 'document' | 'archive' | 'other'
		Mfe: {
			category: string
			config: unknown
			/** Format: date-time */
			created_at: string
			display_name: string
			enabled: boolean
			icon?: string | null
			/** Format: uuid */
			id: string
			module: string
			name: string
			/** Format: int32 */
			order_index: number
			scope: string
			/** Format: date-time */
			updated_at: string
			url: string
			version?: string | null
		}
		NamespaceDTO: {
			/** Format: date-time */
			created_at: string
			description?: string | null
			/** Format: uuid */
			id: string
			is_dynamic: boolean
			name: string
			/** Format: date-time */
			updated_at: string
		}
		NewsDTO: {
			items: components['schemas']['NewsItemDTO'][]
			title: string
		}
		NewsItemDTO: {
			icon: components['schemas']['MediaDTO']
			text: string
		}
		OpportunitiesDTO: {
			items: components['schemas']['OpportunityItemDTO'][]
			title: string
		}
		OpportunityItemDTO: {
			button_text: string
			icon: components['schemas']['MediaDTO']
			items: string[]
			link: string
			title: string
		}
		PaginationDTO: {
			/** Format: int32 */
			limit?: number | null
			/** Format: int32 */
			page: number
			/** Format: int32 */
			total?: number | null
			/** Format: int32 */
			total_pages?: number | null
		}
		PlatformsResponseDTO: {
			description: string
			hero_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			hero_guide_uuid?: string | null
			opportunities: components['schemas']['OpportunitiesDTO']
			opportunities_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			title: string
			tools_and_services: components['schemas']['ToolsAndServicesDTO']
			tools_guide?: null | components['schemas']['MediaDTO']
			/** Format: uuid */
			tools_guide_uuid?: string | null
		}
		ReferralDto: {
			/** Format: int64 */
			count: number
			/** Format: float */
			percentage: number
			source: string
		}
		RegisterRequestDTO: {
			email: string
		}
		RemoteDto: {
			category: string
			config: unknown
			display_name: string
			icon?: string | null
			module: string
			name: string
			/** Format: int32 */
			order: number
			scope: string
			url: string
			version?: string | null
		}
		SearchPromoDTO: {
			description: string
			title: string
		}
		SessionResponseDto: {
			/** Format: uuid */
			id: string
		}
		StartSessionDto: {
			referer?: string | null
			user_agent?: string | null
			/** Format: uuid */
			user_id?: string | null
			/** Format: uuid */
			visitor_id: string
		}
		ToolItemDTO: {
			text: string
			title: string
		}
		ToolsAndServicesDTO: {
			items: components['schemas']['ToolItemDTO'][]
			logo: components['schemas']['MediaDTO']
			title: string
		}
		TrackEventDto: {
			entity_id?: string | null
			entity_type?: string | null
			event_type: string
			path?: string | null
			properties?: unknown
			/** Format: uuid */
			session_id: string
		}
		TrafficStatsDto: {
			dau: number[]
			labels: string[]
			sessions: number[]
		}
		TranslationDTO: {
			/** Format: date-time */
			created_at: string
			/** Format: uuid */
			id: string
			key: string
			locale: string
			/** Format: date-time */
			updated_at: string
			value: string
		}
		TranslationInput: components['schemas']['CreateTranslationDTO'] | components['schemas']['CreateTranslationDTO'][]
		UpdateAboutDTO: {
			description: string
			/** Format: uuid */
			hero_guide_uuid?: string | null
			leadership_description: string
			/** Format: uuid */
			leadership_guide_uuid?: string | null
			leadership_items: components['schemas']['UpdateLeadershipItemDTO'][]
			/** Format: uuid */
			leadership_logo_uuid?: string | null
			leadership_title: string
			/** Format: uuid */
			news_guide_uuid?: string | null
			news_items: components['schemas']['UpdateNewsItemDTO'][]
			news_title: string
			opportunities: components['schemas']['UpdateOpportunityItemDTO'][]
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			title: string
			who_we_are: components['schemas']['UpdateWhoWeAreItemDTO'][]
			/** Format: uuid */
			who_we_are_guide_uuid?: string | null
		}
		UpdateContentEntryDTO: {
			data?: unknown
			i18n?: unknown
			slug?: string | null
			status?: null | components['schemas']['ContentEntryStatus']
		}
		UpdateGuestsDTO: {
			additional_services: components['schemas']['AdditionalServiceDTO'][]
			/** Format: uuid */
			additional_services_guide_uuid?: string | null
			/** Format: uuid */
			hero_guide_uuid?: string | null
			interaction_cards: components['schemas']['InteractionCardDTO'][]
			/** Format: uuid */
			interaction_cards_guide_uuid?: string | null
			opportunities: components['schemas']['GuestOpportunityItemDTO'][]
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			search_promo: components['schemas']['SearchPromoDTO']
			/** Format: uuid */
			search_promo_guide_uuid?: string | null
			title: string
		}
		UpdateLeadershipItemDTO: {
			/** Format: uuid */
			icon_uuid?: string | null
			text: string
		}
		UpdateMediaDTO: {
			alt?: string | null
			category?: string | null
			extension?: string | null
			name?: string | null
			tags?: string[] | null
			title?: string | null
		}
		UpdateMfeDto: {
			category?: string | null
			config?: unknown
			display_name?: string | null
			enabled?: boolean | null
			icon?: string | null
			module?: string | null
			/** Format: int32 */
			order_index?: number | null
			scope?: string | null
			url?: string | null
			version?: string | null
		}
		UpdateNewsItemDTO: {
			/** Format: uuid */
			icon_uuid?: string | null
			text: string
		}
		UpdateOpportunityItemDTO: {
			button_text: string
			/** Format: uuid */
			icon_uuid?: string | null
			items: string[]
			link: string
			title: string
		}
		UpdatePlatformsDTO: {
			description: string
			/** Format: uuid */
			hero_guide_uuid?: string | null
			opportunities: components['schemas']['UpdateOpportunityItemDTO'][]
			/** Format: uuid */
			opportunities_guide_uuid?: string | null
			title: string
			/** Format: uuid */
			tools_guide_uuid?: string | null
			tools_items: components['schemas']['UpdateToolItemDTO'][]
			/** Format: uuid */
			tools_logo_uuid?: string | null
			tools_title: string
		}
		UpdateSchemaDTO: {
			fields?: components['schemas']['FieldDefinition'][] | null
			is_singleton?: boolean | null
			name?: string | null
			slug?: string | null
		}
		UpdateToolItemDTO: {
			text: string
			title: string
		}
		UpdateUserDTO: {
			avatar?: string | null
			/** Format: uuid */
			avatar_uuid?: string | null
			/** Format: date */
			birth_date?: string | null
			city?: string | null
			email?: string | null
			first_name?: string | null
			gender?: string | null
			last_name?: string | null
			phone?: string | null
			role?: null | components['schemas']['UserRole']
			second_name?: string | null
			status?: null | components['schemas']['UserStatus']
			street?: string | null
		}
		UpdateWhoWeAreItemDTO: {
			description: string
			/** Format: uuid */
			image_uuid?: string | null
			title: string
		}
		UserResponseDTO: {
			avatar?: string | null
			/** Format: date */
			birth_date?: string | null
			city?: string | null
			/** Format: date-time */
			created_at: string
			email: string
			first_name?: string | null
			gender?: string | null
			last_name?: string | null
			phone?: string | null
			role: components['schemas']['UserRole']
			second_name?: string | null
			status: components['schemas']['UserStatus']
			street?: string | null
			/** Format: date-time */
			updated_at: string
			/** Format: uuid */
			uuid: string
		}
		/** @enum {string} */
		UserRole: 'superadmin' | 'admin' | 'editor' | 'user'
		/** @enum {string} */
		UserStatus: 'active' | 'inactive' | 'in_moderation'
		WhoWeAreItemDTO: {
			description: string
			image: components['schemas']['MediaDTO']
			title: string
		}
	}
	responses: never
	parameters: never
	requestBodies: never
	headers: never
	pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
	get_about: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AboutResponseDTO']
				}
			}
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AboutResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AboutResponseDTO']
				}
			}
		}
	}
	update_about: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateAboutDTO']
			}
		}
		responses: {
			/** @description About page updated */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_engagement_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Engagement stats */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_EngagementStatsDto']
				}
			}
		}
	}
	get_funnel_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Conversion funnel */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_FunnelStepDto']
				}
			}
		}
	}
	get_referral_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Referral sources */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_ReferralDto']
				}
			}
		}
	}
	get_retention_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description User retention cohorts */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_CohortRowDto']
				}
			}
		}
	}
	start_session: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['StartSessionDto']
			}
		}
		responses: {
			/** @description Session started */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_SessionResponseDto']
				}
			}
		}
	}
	get_summary_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Analytics summary */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AnalyticsSummaryDto']
				}
			}
		}
	}
	track_event: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['TrackEventDto']
			}
		}
		responses: {
			/** @description Event tracked */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_traffic_stats: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Traffic stats */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_TrafficStatsDto']
				}
			}
		}
	}
	login: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['AuthRequestDTO']
			}
		}
		responses: {
			/** @description Успешно */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
			/** @description Неверные учетные данные */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
			/** @description Ошибка базы данных */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
		}
	}
	logout: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['AuthResponseDTO']
			}
		}
		responses: {
			/** @description Успешный выход */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка базы данных */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	logout_other_devices: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['AuthRefreshTokenDTO']
			}
		}
		responses: {
			/** @description Другие сессии завершены */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка базы данных */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	refresh: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['AuthRefreshTokenDTO']
			}
		}
		responses: {
			/** @description Успешное обновление токена */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
			/** @description Refresh-токен недействителен или истек */
			401: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
			/** @description Ошибка базы данных */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_AuthResponseDTO']
				}
			}
		}
	}
	register: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['RegisterRequestDTO']
			}
		}
		responses: {
			/** @description Письмо отправлено */
			201: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Некорректный email */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Email уже используется */
			409: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка сервера */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	check_register_key: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CheckEmailCodeDTO']
			}
		}
		responses: {
			/** @description Код действителен */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Некорректный код */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Код не найден или истёк */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка сервера */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	create_entry: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateContentEntryDTO']
			}
		}
		responses: {
			201: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentEntry']
				}
			}
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_entry: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Entry ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentEntry']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_entry: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Entry ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Value']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	update_entry: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Entry ID */
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateContentEntryDTO']
			}
		}
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentEntry']
				}
			}
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_entry_versions: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Entry ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_ContentEntryVersion']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	rollback_entry_version: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Entry ID */
				id: string
				/** @description Version ID */
				version_id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentEntry']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_schemas: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_ContentSchema']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	create_schema: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateSchemaDTO']
			}
		}
		responses: {
			201: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentSchema']
				}
			}
			/** @description Bad Request */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_schema: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Schema ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentSchema']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_schema: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Schema ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Value']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	update_schema: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Schema ID */
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateSchemaDTO']
			}
		}
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_ContentSchema']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not Found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_entries: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Schema ID */
				schema_id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_ContentEntry']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal Server Error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_features: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Success */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	update_features: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['FeatureFlagsUpdate']
			}
		}
		responses: {
			/** @description Success */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_guests: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_GuestsResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_GuestsResponseDTO']
				}
			}
		}
	}
	update_guests: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateGuestsDTO']
			}
		}
		responses: {
			/** @description Guests page updated */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_all: {
		parameters: {
			query: {
				/** @description Locale code, e.g. 'en', 'ru' */
				locale: string
				/** @description Page number */
				page: number
				/** @description Items per page */
				limit: number
				/** @description Search query */
				search: string
				/** @description Namespace filter */
				namespace: string
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Translations loaded */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponseWithPagination_TranslationDTO']
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	create_or_update: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['TranslationInput']
			}
		}
		responses: {
			/** @description Translation(s) created or updated */
			201: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_languages: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of available languages */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_LanguageDTO']
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_namespaces: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of available namespaces */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_NamespaceDTO']
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_by_dict_key: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Dictionary key prefix, e.g. 'user', 'general' */
				dict_key: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Translations loaded */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': Record<string, never>
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_one: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Translation key */
				key: string
				/** @description Locale code */
				locale: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Translation deleted */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_all_media: {
		parameters: {
			query: {
				/** @description Page number */
				page: number
				/** @description Items per page */
				limit: number
			}
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description List of media with pagination */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponseWithPagination_MediaItemDTO']
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponseWithPagination_MediaItemDTO']
				}
			}
		}
	}
	upload_media: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'multipart/form-data': components['schemas']['CreateMediaDTO'][]
			}
		}
		responses: {
			/** @description Media uploaded successfully */
			201: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Value']
				}
			}
			/** @description Invalid request */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Quota exceeded */
			413: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_all_media: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description All media deleted successfully */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Value']
				}
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_media_by_uuid: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Media UUID */
				uuid: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Media item fetched successfully */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_MediaItemDTO']
				}
			}
			/** @description Media not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	update_media: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Media UUID */
				uuid: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateMediaDTO']
			}
		}
		responses: {
			/** @description Media updated successfully */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_MediaItemDTO']
				}
			}
			/** @description Media not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_media_by_uuid: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description Media UUID */
				uuid: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Media deleted successfully */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Value']
				}
			}
			/** @description Media not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Internal server error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_all: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description All microfrontends list */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_Vec_Mfe']
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	create: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateMfeDto']
			}
		}
		responses: {
			/** @description Microfrontend created */
			201: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Bad request */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_manifest: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Dynamic manifest generated */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ManifestDto']
				}
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	update: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description MFE ID */
				id: string
			}
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateMfeDto']
			}
		}
		responses: {
			/** @description Microfrontend updated */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	delete_one: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description MFE ID */
				id: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Microfrontend deleted */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Not found */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_platforms: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_PlatformsResponseDTO']
				}
			}
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_PlatformsResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_PlatformsResponseDTO']
				}
			}
		}
	}
	update_platforms: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdatePlatformsDTO']
			}
		}
		responses: {
			/** @description Platforms page updated */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Database error */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_health: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description System health status */
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['HealthStatus']
				}
			}
		}
	}
	get_stats_stream: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Stream system statistics via SSE */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	create_user: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['CreateUserDTO']
			}
		}
		responses: {
			/** @description Пользователь создан */
			201: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Пользователь существует */
			409: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Внутренняя ошибка */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_me: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
		}
	}
	update_me: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['UpdateUserDTO']
			}
		}
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
		}
	}
	change_password: {
		parameters: {
			query?: never
			header?: never
			path?: never
			cookie?: never
		}
		requestBody: {
			content: {
				'application/json': components['schemas']['ChangePasswordDTO']
			}
		}
		responses: {
			/** @description Пароль изменен */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Неверный старый пароль */
			400: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Unauthorized */
			401: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
	get_user_by_uuid: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description User UUID */
				uuid: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			200: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			404: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
			500: {
				headers: {
					[name: string]: unknown
				}
				content: {
					'application/json': components['schemas']['ApiResponse_UserResponseDTO']
				}
			}
		}
	}
	delete_user_by_uuid: {
		parameters: {
			query?: never
			header?: never
			path: {
				/** @description User UUID */
				uuid: string
			}
			cookie?: never
		}
		requestBody?: never
		responses: {
			/** @description Пользователь удален */
			200: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Не найден */
			404: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
			/** @description Ошибка базы данных */
			500: {
				headers: {
					[name: string]: unknown
				}
				content?: never
			}
		}
	}
}
