use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use serde_json::Value as JsonValue;
use sqlx::FromRow;
use utoipa::ToSchema;
use uuid::Uuid;

#[derive(Debug, Serialize, Deserialize, FromRow, ToSchema, Clone)]
pub struct Venue {
    pub id: Uuid,
    pub slug: String,
    pub title: String,
    pub subtitle: Option<String>,
    pub description_html: Option<String>,
    pub phone: Option<String>,
    pub address: String,
    pub city: String,
    pub metro_station: Option<String>,
    pub metro_distance_minutes: Option<i32>,
    pub metro_distance_text: Option<String>,
    pub metro_line_color: Option<String>,
    pub coordinates_lat: Option<f64>,
    pub coordinates_lng: Option<f64>,
    pub average_check: Option<i32>,
    pub banquet_price_from: Option<i32>,
    pub rent_price_hour: Option<i32>,
    pub corkage_fee_has: Option<bool>,
    pub corkage_fee_desc: Option<String>,
    pub price_level: Option<String>,
    pub halls_count: Option<i32>,
    pub capacity_banquet: Option<String>,
    pub capacity_buffet: Option<String>,
    pub capacity_theater: Option<String>,
    pub area_sqm: Option<String>,
    pub working_hours_weekdays: Option<String>,
    pub working_hours_weekends: Option<String>,
    pub rating_score: Option<f64>,
    pub rating_reviews_count: Option<i32>,
    pub venue_types: Option<Vec<String>>,
    pub features: Option<Vec<String>>,
    pub cuisines: Option<Vec<String>>,
    pub services: Option<Vec<String>>,
    pub parking: Option<String>,
    pub equipment: Option<Vec<String>>,
    pub halls: Option<JsonValue>,
    pub rooms: Option<JsonValue>,
    pub gallery_photos: Option<Vec<String>>,
    pub video_tour_url: Option<String>,
    pub has_online_tour: Option<bool>,
    pub faq: Option<JsonValue>,
    pub feed: Option<JsonValue>,
    pub menu_photos: Option<Vec<String>>,
    pub reviews: Option<JsonValue>,
    pub pricing_table: Option<JsonValue>,
    pub menu_url: Option<String>,
    pub rider_url: Option<String>,
    pub status: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Debug, Deserialize, ToSchema, Clone)]
pub struct CreateVenueDTO {
    pub slug: String,
    pub title: String,
    pub subtitle: Option<String>,
    pub description_html: Option<String>,
    pub phone: Option<String>,
    pub address: String,
    pub city: Option<String>,
    pub metro_station: Option<String>,
    pub metro_distance_minutes: Option<i32>,
    pub metro_distance_text: Option<String>,
    pub metro_line_color: Option<String>,
    pub coordinates_lat: Option<f64>,
    pub coordinates_lng: Option<f64>,
    pub average_check: Option<i32>,
    pub banquet_price_from: Option<i32>,
    pub rent_price_hour: Option<i32>,
    pub corkage_fee_has: Option<bool>,
    pub corkage_fee_desc: Option<String>,
    pub price_level: Option<String>,
    pub halls_count: Option<i32>,
    pub capacity_banquet: Option<String>,
    pub capacity_buffet: Option<String>,
    pub capacity_theater: Option<String>,
    pub area_sqm: Option<String>,
    pub working_hours_weekdays: Option<String>,
    pub working_hours_weekends: Option<String>,
    pub rating_score: Option<f64>,
    pub rating_reviews_count: Option<i32>,
    pub venue_types: Option<Vec<String>>,
    pub features: Option<Vec<String>>,
    pub cuisines: Option<Vec<String>>,
    pub services: Option<Vec<String>>,
    pub parking: Option<String>,
    pub equipment: Option<Vec<String>>,
    pub halls: Option<JsonValue>,
    pub rooms: Option<JsonValue>,
    pub gallery_photos: Option<Vec<String>>,
    pub video_tour_url: Option<String>,
    pub has_online_tour: Option<bool>,
    pub faq: Option<JsonValue>,
    pub feed: Option<JsonValue>,
    pub menu_photos: Option<Vec<String>>,
    pub reviews: Option<JsonValue>,
    pub pricing_table: Option<JsonValue>,
    pub menu_url: Option<String>,
    pub rider_url: Option<String>,
    pub status: Option<String>,
}

#[derive(Debug, Deserialize, ToSchema, Clone)]
pub struct UpdateVenueDTO {
    pub slug: Option<String>,
    pub title: Option<String>,
    pub subtitle: Option<String>,
    pub description_html: Option<String>,
    pub phone: Option<String>,
    pub address: Option<String>,
    pub city: Option<String>,
    pub metro_station: Option<String>,
    pub metro_distance_minutes: Option<i32>,
    pub metro_distance_text: Option<String>,
    pub metro_line_color: Option<String>,
    pub coordinates_lat: Option<f64>,
    pub coordinates_lng: Option<f64>,
    pub average_check: Option<i32>,
    pub banquet_price_from: Option<i32>,
    pub rent_price_hour: Option<i32>,
    pub corkage_fee_has: Option<bool>,
    pub corkage_fee_desc: Option<String>,
    pub price_level: Option<String>,
    pub halls_count: Option<i32>,
    pub capacity_banquet: Option<String>,
    pub capacity_buffet: Option<String>,
    pub capacity_theater: Option<String>,
    pub area_sqm: Option<String>,
    pub working_hours_weekdays: Option<String>,
    pub working_hours_weekends: Option<String>,
    pub rating_score: Option<f64>,
    pub rating_reviews_count: Option<i32>,
    pub venue_types: Option<Vec<String>>,
    pub features: Option<Vec<String>>,
    pub cuisines: Option<Vec<String>>,
    pub services: Option<Vec<String>>,
    pub parking: Option<String>,
    pub equipment: Option<Vec<String>>,
    pub halls: Option<JsonValue>,
    pub rooms: Option<JsonValue>,
    pub gallery_photos: Option<Vec<String>>,
    pub video_tour_url: Option<String>,
    pub has_online_tour: Option<bool>,
    pub faq: Option<JsonValue>,
    pub feed: Option<JsonValue>,
    pub menu_photos: Option<Vec<String>>,
    pub reviews: Option<JsonValue>,
    pub pricing_table: Option<JsonValue>,
    pub menu_url: Option<String>,
    pub rider_url: Option<String>,
    pub status: Option<String>,
}
